### ISSUE TITLE
Body not in form of JSON

### ISSUE THREAD

**Issue by rlcurrall** [Sweylo/CSCI_470_STV_BACKEND#2]
Some requests have responses that are not in for of JSON, this causes an issue when JSON is expected on the client end. The issue only exists in the **_gameplay_actions.php_** file. 

Line 19
`send_to_client(401, null, 'must be logged in');`
Line 25
`send_to_client(400, null, 'you are not in a match');`
Line 81
`send_to_client(400, null, 'you are not in a match');`
Line 83
`send_to_client(202, null, 'waiting for opponent to ready');`

I can set it to where the response code is used to handle errors if needed.

**Comment by Sweylo** [comment]
Laziness. I've been meaning to create constants to refer to these but yeah. So now there are some. The will look like: { "match_error": 1 }. For non-error messages, it will be { "match_message": 1 }. The values corresponding to the messages are as follows

// error constants
const MATCH_ERROR_NOT_LOGGED_IN = 1;
const MATCH_ERROR_NOT_IN_A_MATCH = 2;

// message constants
const MATCH_MESSAGE_WAITING_FOR_OPPONENT_READY = 1;
const MATCH_MESSAGE_MATCH_IS_STARTING = 2;
