### ISSUE TITLE
Send Selected Cards With 'ready_to_play' Request

### ISSUE THREAD

**Issue by rlcurrall** [Sweylo/CSCI_470_STV_BACKEND#4]
We need to have a way to send what cards the user selected with the 'ready_to_play' request. This also includes a way to indicate what square any trap cards will be placed on if the user is going to use a trap card.

**Comment by Sweylo** [comment]
I would say something like this: 

{
    "action": "ready_to_play",
    "cards": [
        { // trap card
            "card_id": 1,
            "space_id": 1
        },
         { // power card, if needed, can't remember
            "card_id": 1,
            "piece_id": 1
        }
    ]
}

Just an array containing card ids and space ids. I may be mistaken but I think pieces could be powered up at the beginning too. If so, then just do card id and piece id, if not, ignore that bit. These would also be based on the relative ids that were mentioned in issue #5 . I realize now that I did these in reverse order.
