### ISSUE TITLE
Space_id & piece_id no longer following usual pattern of numbering

### ISSUE THREAD

**Issue by rlcurrall** [Sweylo/CSCI_470_STV_BACKEND#5]
**This is only an issue if through the API I am sending you the space ID and piece ID when moving pieces, if we are using relative data it has no bearing**
As we discussed before, I did not need the piece ID or space ID because the could be derived from the match id using the following:

- piece_id = (32 * match_id) + 1 // there are 32 pieces and pieces index starts at 1

- space_id = (64 * match_id) + 1

I am using the webUI to verify this, but I created a match, match #30, which had irregular piece & space ids. This first _piece_ of this match should be **961** but is **577**, and the first _space_ of this match should be **1921** but is **1153**, both of which corresponds to **match 18** not **30**.

From what I can tell is that when a match is created and no other user joins the match, the pieces are not populated in the DB, and there have been many matches that I have made that I deleted before I had a second user join, 12 apparently. This will be a problem if we allow users to cancel a match they have created before a user has join the match.

From here we have three possible fixes, we can either change the 'create_match' request to call both the _add_match()_ function and the _init_match()_ function so that the spaces and pieces are populated in the database. The other option would be to send the space ID of the first space, and the piece ID of the first piece to the users when the match is created. Finally, the final option would be to setup the move_piece request to send relative data through concatenating the IDs such as:
pieceID = matchID_1
To indicate the first piece in the match.

**Comment by Sweylo** [comment]
I think I will add an additional field in the database for relative ids. I'm not convinced that method will always produce unique ids for every match so I'll keep the primary key being what they are now: generated by mysql. But for all front-end purposes the server will translate into that format given a match id and relative piece or space id.
